### ISSUE TITLE
filter done/cancelled

### ISSUE THREAD

**Issue by hodanli** [ahonn/logseq-plugin-hide-everything#1]
hi,

thanks for great plug-in. is it possible to add cancelled and done blocks.

best.

**Comment by ahonn** [comment]
I don't quite understand the meaning of "add cancelled and done blocks." Can you explain it? 
Are you referring to the completed TODO block?

**Comment by yoghurtdewdew** [comment]
I have the same need! I really hope to hide todos by their type, or just look at them respectively.

e.g. Hide/Only-show done/cancelled/WAITING/Later/now/todo/doing/in-progress… Hide/Only-show todos/no-todos…

Sounds more like a filter, but I am unable to make dynamic filters for each kinds of varying days.

**Comment by yoghurtdewdew** [comment]
Hope there will be some ways to hide done/cancelled to keep the page clean.

Is there some new progress?

**Comment by ahonn** [comment]
@hodanli @yoghurtdewdew 
Yesterday I released a new version, which added the feature of hiding completed/canceled tasks.
Please upgrade the plugin version to v1.1.0

**Comment by yoghurtdewdew** [comment]
Thanks for your great work! It just worked perfectly!

I'm not sure there will be an enhancement as mentioned in https://github.com/ahonn/logseq-plugin-hide-everything/issues/1#issuecomment-1605347589

Thanks again!

**Comment by ahonn** [comment]
> Thanks for your great work! It just worked perfectly!
> 
> I'm not sure there will be an enhancement as mentioned in [#1 (comment)](https://github.com/ahonn/logseq-plugin-hide-everything/issues/1#issuecomment-1605347589)
> 
> Thanks again!

@yoghurtdewdew 
I probably won't implement this in this plugin. The purpose of this plugin is simply to hide unnecessary elements on the page, not specifically for todos.

Perhaps I can add the corresponding functionality to my other plugin https://github.com/ahonn/logseq-plugin-todo, but I'm not sure yet. I'm still considering it. What do you think about this?

**Comment by yoghurtdewdew** [comment]
I think that would be nice! It already shows what about today, but it always shows the todos from journals before today.
I have a lot of _later_ todos in journals and pages, so the popup with all the _later_ of everything showed in the popup would make me confused of choose them to do. 

I suggest that:
filter-pages: this page, journals, all pages
filter-date: today, yesterday, 1 week ago, 1 month ago, in 1 week, in 1 month, custom: ± x days
filter-marker: later now waiting todo doing done cancelled all custom:checkbox-multi
filter-keywords: custom 

collapse & pin button: I could click to collapse a page if I want to hide it to focus on others. I could see a page on top so reminder me remember this or focus on this.

Look forward to the enhancement of your plugin https://github.com/ahonn/logseq-plugin-todo !
